name: Cypress Tests

on: [push]

jobs:
  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set the appropriate Node.js version

      - name: Install Node.js dependencies
        run: yarn
        working-directory: ./todomvc

      - name: Server build
        run: yarn run cypress:run"
        working-directory: ./todomvc
